version: 2
jobs:
  build:
    working_directory: /go/src/github.com/gjbae1212/gossm

    branches:
      only:
        - master

    docker:
      - image: golang:1.17

    environment:
      GOPATH: /go

    steps:
      - checkout
      - run:
          name: RUN UNIT TEST
          environment:
            GO111MODULE: "on"
          command: bash scripts/deploy.sh test_with_circleci
